TicketID/GDESK.WEB/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using GDESK.CORE.Enum;
using GDESK.CORE.Filter;
using GDESK.CORE.Service;
using GDESK.CORE.Service.Interface;
using GDESK.CORE.UserControl;
using GDESK.CORE.ViewModel.Control;
using GDESK.CORE.ViewModel.Page;

namespace GDESK.WEB.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly IAnexoService _anexoService;
        private readonly IUsuarioService _usuarioService;
        private readonly IEmpresaService _empresaService;

        public string GuidId
        {
            get { return Guid.NewGuid().ToString(); }
        }

        public UsuarioController()
        {
            _anexoService = new AnexoService();
            _usuarioService = new UsuarioService();
            _empresaService = new EmpresaService();
        }

        public ActionResult Autenticar()
        {
            var session = Sessions.UsuarioLogado;

            if (session == null)
            {
                Sessions.Abas.Clear();
                return View();
            }
            

            var model = new ViewModelLogin { Login = session.Login, Senha = session.Senha };
            _usuarioService.Autenticar(model);

            return RedirectToAction("Principal", "Chamado");
        }

        [HttpPost]
        public ActionResult Autenticar(ViewModelLogin model)
        {
            var url = Url.Action("Principal", "Chamado");

            if (!string.IsNullOrEmpty(model.UrlDefault))
                url = model.UrlDefault;

            if (_usuarioService.Autenticar(model)) return Json(url);

            return new HttpStatusCodeResult(HttpStatusCode.Conflict, "Fault");
        }


        [HttpPost]
        public ActionResult Cadastrar(UsuarioViewModel model)
        {
           
             var codAnexo = 1; //~/Profiles/padrao.jpg padrão

            if (Sessions.Anexos.Any())
                codAnexo = _anexoService.Adicionar(Sessions.Anexos.First());

            Sessions.Anexos.Clear();

            model.CodigoAnexo = codAnexo;
            _usuarioService.AdicionarUsuario(model);

            var login = new ViewModelLogin { Login = model.Login, Senha = model.Senha };

            return Json(_usuarioService.Autenticar(login) ? Url.Action("Principal", "Chamado") : "Fault");
        }

        [Authorize]
        public ActionResult Alterar()
        {
            var model = Suporte.UsuarioLogado;
            return View(model);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Alterar(UsuarioViewModel model)
        {
    
            if (model == null) throw new ArgumentNullException("model");

            if (Sessions.Anexos.Any())
                model.CodigoAnexo = _anexoService.Adicionar(Sessions.Anexos.First());

            Sessions.Anexos.Clear();

            _usuarioService.AlterarUsuario(model);

            Sessions.UsuarioLogado = _usuarioService.ObterUsuario(model.CodigoUsuario);

            return View(Suporte.UsuarioLogado);
        }

        [TrocarStatusChamadoFilter]
        [Authorize]
        public ActionResult Deslogar()
        {
            _usuarioService.Logout();

            return RedirectToAction("Autenticar");
        }

       
        [HttpPost]
        public ActionResult UploadProfile()
        {
            var fileName = string.Empty;
            var pathFile = string.Empty;
            const string mensagem = " Arquivo recebido com êxito !";


            foreach (var anexo in from string file in Request.Files select Request.Files[file])
            {
                var fileToSave = GuidId + Path.GetExtension(anexo.FileName);
                pathFile = Path.Combine("~/Profiles", fileToSave);
                fileName = anexo.FileName;


                _anexoService
                    .FileName(Server.MapPath(pathFile))
                    .Arquivo(anexo);

                if (Sessions.Anexos.Any())
                    _anexoService.Deletar(Server.MapPath(Sessions.Anexos.First().CaminhoArquivo));

                Sessions.Anexos = new List<AnexoViewModel> { new AnexoViewModel { CaminhoArquivo = pathFile, NomeArquivo = anexo.FileName } };

                _anexoService.Anexar(DestinoAnexoEnum.Abrir);


            }

            return Json(new { FileName = fileName, Mensagem = mensagem, PathName = pathFile });
        }


        #region JSONRESULT

       
        public JsonResult VerificaEmpresa(string cnpj)
        {
            var empresa = _empresaService.VerificaEmpresa(cnpj);


            return Json(new { Existe = empresa != null, NomeEmpresa = empresa != null ? empresa.Nome : "Invalido", CodigoEmpresa = empresa != null ? empresa.CodigoEmpresa : 0 }, JsonRequestBehavior.AllowGet);
        }
        
        public JsonResult VerificaUsuario(string usuarioNome)
        {
            var usuario = _usuarioService.VerificaUsuario(usuarioNome);

            return Json(new { Existe = usuario != null, NomeUsuario = usuario != null ? usuario.Nome : "Invalido", CodigoUsuario = usuario != null ? usuario.CodigoUsuario : 0 }, JsonRequestBehavior.AllowGet);
        }


        #endregion

    }
}

TicketID/GDESK.WEB/Views/Usuario/Alterar.cshtml
@model GDESK.CORE.ViewModel.Page.UsuarioViewModel

@{
    ViewBag.Title = "Alterar";
    Layout = "~/Views/Layouts/_LayoutMain.cshtml";
    ViewBag.Header = "Alterar Dados";
}

<!-- CONTEUDO AQUI -->
<div class="row">
    <div class="col-md-12">
        <div class="widget no-margin">
            <div class="widget-header">
                <div class="title">
                    <span class="fs1" aria-hidden="true" data-icon=""></span>Alterar Dados
                </div>
            </div>
            <div class="widget-body">
                <div class="row">
                    <div class="col-md-2 col-sm-3">
                        <div class="thumbnail">
                            <img id="fotoPerfil" alt="300x200" src="@Url.Content(Model.FileName)">
                        </div>
                    </div>
                    <div class="col-md-10 col-sm-9">
                        @using (Html.BeginForm("Alterar", "Usuario", FormMethod.Post, new { @class = "form-horizontal",id = "frmAlterar"}))
                        {
                          
                            <h3 class="heading-a">Geral</h3>
                            <div class="form-group">
                                <label for="userName" class="col-sm-2 control-label ">Empresa</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" name="@Html.NameFor(x=>x.Empresa)" placeholder="@Html.DisplayFor(x => x.Empresa)" disabled>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="userName" class="col-sm-2 control-label">Nome</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" value="@Html.DisplayFor(x => x.Nome)" name="@Html.NameFor(x=>x.Nome)" placeholder="Nome">
                                    <input type="hidden" class="form-control" value="@Html.DisplayFor(x => x.CodigoUsuario)" name="@Html.NameFor(x=>x.CodigoUsuario)">
                                    <input type="hidden" class="form-control" value="@Html.DisplayFor(x => x.CodigoAnexo)" name="@Html.NameFor(x=>x.CodigoAnexo)">
                                </div>
                            </div>
                            <h3 class="heading-a">Contato</h3>
                            <div class="form-group">
                                <label for="emilId" class="col-sm-2 control-label">Email</label>
                                <div class="col-sm-10">
                                    <input type="email" class="form-control" value="@Html.DisplayFor(x => x.Email)" name="@Html.NameFor(x=>x.Email)" placeholder="Email">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="phone" class="col-sm-2 control-label">Celular</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" name="@Html.NameFor(x=>x.Celular)" value="@Convert.ToInt64(Model.Celular).ToString("(##) #####-####")"  placeholder="Celular">
                                </div>
                            </div>


                            <h3 class="heading-a">Segurança</h3>
                            <div class="form-group">
                                <label for="phone" class="col-sm-2 control-label">Senha</label>
                                <div class="col-sm-10">
                                    <input type="password" class="form-control" name="@Html.NameFor(x=>x.Senha)" value="@Html.DisplayFor(x => x.Senha)"  placeholder="*********">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="password" class="col-sm-2 control-label">Confirmar</label>
                                <div class="col-sm-10">
                                    <input type="password" class="form-control" name="ConfirmarSenha" value="@Html.DisplayFor(x => x.Senha)" placeholder="*********">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-10 col-sm-offset-2">
                                    <input type="file" class="filestyle pull-left" data-buttontext="Foto perfil" data-classbutton="btn btn-primary" data-input="true" id="fileupload" accept="image/x-png, image/gif, image/jpeg">
                                    <br />
                                    <br />
                                    <div class="progress" style="height: 3px">
                                        <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0">
                                            <span class="sr-only">0% Complete</span>
                                        </div>
                                    </div>
                                    <div class="alert alert-info" id="Mensangem" style="display: none">
                                    </div>
                                </div>
                            </div>
                            <div class="form_submit clearfix" style="">
                                <div class="row">
                                    <div class="col-sm-10 col-sm-offset-2">
                                        <input type="submit" class="btn btn-primary btn-lg pull-right" name='btnSalvar' value="Salvar">
                                    </div>
                                </div>
                            </div>

                           
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- FIM CONTEUDO AQUI -->
<script src="@Url.Content("~/Content/js/jquery.ui.widget.js")"></script>
<script src="@Url.Content("~/Content/js/jquery.fileupload.js")"></script>
<script type="text/javascript">
    $(function () {
        UploadProfile();
        $("#frmAlterar input[name=Celular]").focusout(function () {
            var phone, element;
            element = $(this);
            element.unmask();
            phone = element.val().replace(/\D/g, '');
            if (phone.length > 10) {
                element.mask("(99) 99999-999?9");
            } else {
                element.mask("(99) 9999-9999?9");
            }
        }).trigger('focusout');

        $("#frmAlterar").validate({
            rules: {
                Nome: { required: true },
                Email: { required: true, email: true },
                Celular: { required: true },
                Login: { required: true },
                Senha: { required: true },
                ConfirmarSenha: { equalTo: $("#frmAlterar input[name=Senha]") }
                
            },
            messages: {
                Nome: "Seu nome é obrigatorio",
                Email: "Insira um email valido",
                Celular: "Celular é obrigatorio",
                Login: "Usuario é obrigatorio",
                Senha: "Senha é obrigatorio",
                ConfirmarSenha:"Senha não confere"
            }
        });
    });

    function UploadProfile() {
        $('#fileupload').fileupload({
            dataType: 'json',
            url: '/Usuario/UploadProfile',
            autoUpload: true,
            acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i,
            done: function (e, data) {
                $("#Mensangem").show();
                var fileHtml = "<strong data-url=" + data.result.PathName + ">" + data.result.FileName + "</strong> " + data.result.Mensagem + "</br>";
                $("#Mensangem").html($(fileHtml).fadeToggle('slow'));
                $("#fotoPerfil").attr("src", $("#Mensangem strong").data("url").replace('~', ''));
                
            }
        }).on('fileuploadprogressall', function (e, data) {
            var progress = parseInt(data.loaded / data.total * 100, 10);
            $('.progress .progress-bar').css('width', progress + '%');
            $('.progress .progress-bar').attr('aria-valuenow', progress);

        });
    }



</script>

TicketID/GDESK.WEB/Views/Usuario/Autenticar.cshtml
@using GDESK.CORE.ViewModel.Control
@{
    ViewBag.Title = "Autenticar";
    Layout = "~/Views/Layouts/_LayoutLogin.cshtml";
}

@Html.Partial("~/UserControl/Usuario/_PartialLogin.cshtml",new ViewModelLogin())
@Html.Partial("~/UserControl/Usuario/_PartialCadastrarModal.cshtml"))